### ISSUE TITLE
XSS module doesnt sanitize xss vectors in broken html 

### ISSUE THREAD

**Issue by TDA** [leizongmin/js-xss#40]
## STR:
Run the xss module on the following contents:
```
Hesabı təsdiqlə:

Xətalı istək

Səhifə tapılmadı
Cuenta desconocida. <a href="javascript(1)" onclick="javascript:alert('hey')

Desconectado correctamente

La cuenta ya existe. <a href="/signin">Identifícate</a>
```

## Expected Behavior:
* Error on finding xss vector (javascript) and/or cleaning that up

## Actual behavior
* No errors or cleaning up.

More detailed examples at https://github.com/mozilla/fxa-content-server-l10n/pull/63
@shane-tomlinson

**Comment by leizongmin** [comment]
The problem is `onclick=` is start with a `"`, so it need the same `"` to close, then the following is an attribute and value:

```
onclick="javascript:alert('hey')

Desconectado correctamente

La cuenta ya existe. <a href="
```

the next attribute is `/signin` and `">Identifícate</a>`(it need a `"` to close)

so if we add a `"` to the end, for example:

```html
<a href="javascript(1)" onclick="javascript:alert('hey')

Desconectado correctamente

La cuenta ya existe. <a href="/signin">Identifícate</a>"

<a href="#">it wroks</a>
```

the following `<a>` tag is OK:

```html
&lt;a href="javascript(1)" onclick="javascript:alert('hey')

Desconectado correctamente

La cuenta ya existe. &lt;a href="/signin"&gt;Identifícate&lt;/a&gt;"

<a href="#">it wroks</a>
```

------

I think I should fix this problem, but I don't know when to automatically close the broken HTML tag.

**Comment by leizongmin** [comment]
@TDA I have fixed this problem, when input the uper deformity  HTML,  the latest version will output:

```
Hesabı təsdiqlə:

Xətalı istək

Səhifə tapılmadı
Cuenta desconocida. <a href>Identifícate</a>
```

please install the latest version `xss@0.2.7`

**Comment by TDA** [comment]
@leizongmin Thank you so much! :)
